### PR TITLE
Removed crcmod dependency.

### PR DESCRIPTION
**Pull request by Illidanz**
crcmod is a pretty old package and has some trouble getting installed on machines without build tools since it's using a C extension.

Tested on a few roms and it produced the same checksum as the original function.

### CODE REVIEW

**Comment by RoadrunnerWMC** [comment]
Thanks! I'll remove mention of it from the documentation and setup script before merging.

**Comment by Illidanz** [comment]
@RoadrunnerWMC Sorry for the ping, any chance you could push a new release to pypi with this change in? The crcmod dependancy is breaking support for certain platforms for a library I'm writing and the new release would help a lot.

**Comment by RoadrunnerWMC** [comment]
Sorry for the late reply, I just saw this. I'll make a new release soon.

**Comment by RoadrunnerWMC** [comment]
ndspy 4.1.0 is now available [on GitHub](https://github.com/RoadrunnerWMC/ndspy/releases/tag/v4.1.0) and [PyPI](https://pypi.org/project/ndspy/).

I've also enabled email notifications on my GitHub account so that I'll be less likely to miss activity on this repo (and others) in the future. Sorry about that again.

**Comment by Illidanz** [comment]
No worries, thanks a lot for the release!

**Pull request merged**
